/**
 * 500 Curated Available Fonts for booktomes
 * Dynamic Google Fonts loader utility supporting 500 distinct fonts
 * across Playful/Comic, Storybook Serif, Friendly Sans, Handwriting, and Display.
 */

export interface FontOption {
  name: string;
  category: 'Comic & Playful' | 'Storybook Serif' | 'Friendly Sans' | 'Handwritten' | 'Display & Creative' | 'Monospace';
}

// 500 distinct Google Fonts categorized for children's books and creative reading
export const AVAILABLE_FONTS: FontOption[] = [
  // --- Comic & Playful (80 fonts) ---
  { name: 'Cortez', category: 'Comic & Playful' },
  { name: 'Fredoka', category: 'Comic & Playful' },
  { name: 'Bubblegum Sans', category: 'Comic & Playful' },
  { name: 'Comic Neue', category: 'Comic & Playful' },
  { name: 'Sniglet', category: 'Comic & Playful' },
  { name: 'Chango', category: 'Comic & Playful' },
  { name: 'Boogaloo', category: 'Comic & Playful' },
  { name: 'Chewy', category: 'Comic & Playful' },
  { name: 'Bangers', category: 'Comic & Playful' },
  { name: 'Luckiest Guy', category: 'Comic & Playful' },
  { name: 'Creepster', category: 'Comic & Playful' },
  { name: 'Ribeye', category: 'Comic & Playful' },
  { name: 'Ribeye Marrow', category: 'Comic & Playful' },
  { name: 'Titan One', category: 'Comic & Playful' },
  { name: 'Spicy Rice', category: 'Comic & Playful' },
  { name: 'Gochi Hand', category: 'Comic & Playful' },
  { name: 'Original Surfer', category: 'Comic & Playful' },
  { name: 'Slackey', category: 'Comic & Playful' },
  { name: 'Fontdiner Swanky', category: 'Comic & Playful' },
  { name: 'Frijole', category: 'Comic & Playful' },
  { name: 'Shojumaru', category: 'Comic & Playful' },
  { name: 'Ranchers', category: 'Comic & Playful' },
  { name: 'Modak', category: 'Comic & Playful' },
  { name: 'Emilys Candy', category: 'Comic & Playful' },
  { name: 'Flavors', category: 'Comic & Playful' },
  { name: 'Joti One', category: 'Comic & Playful' },
  { name: 'Chicle', category: 'Comic & Playful' },
  { name: 'Milonga', category: 'Comic & Playful' },
  { name: 'Freckle Face', category: 'Comic & Playful' },
  { name: 'Irish Grover', category: 'Comic & Playful' },
  { name: 'Mountains of Christmas', category: 'Comic & Playful' },
  { name: 'Eater', category: 'Comic & Playful' },
  { name: 'Finger Paint', category: 'Comic & Playful' },
  { name: 'Kavoon', category: 'Comic & Playful' },
  { name: 'Wendy One', category: 'Comic & Playful' },
  { name: 'Skranji', category: 'Comic & Playful' },
  { name: 'Jolly Lodger', category: 'Comic & Playful' },
  { name: 'Mystery Quest', category: 'Comic & Playful' },
  { name: 'Nosifer', category: 'Comic & Playful' },
  { name: 'Piedra', category: 'Comic & Playful' },
  { name: 'Peralta', category: 'Comic & Playful' },
  { name: 'Smokum', category: 'Comic & Playful' },
  { name: 'Vampiro One', category: 'Comic & Playful' },
  { name: 'Griffy', category: 'Comic & Playful' },
  { name: 'Bigelow Rules', category: 'Comic & Playful' },
  { name: 'Trade Winds', category: 'Comic & Playful' },
  { name: 'Underwood', category: 'Comic & Playful' },
  { name: 'Kirang Haerang', category: 'Comic & Playful' },
  { name: 'Unkempt', category: 'Comic & Playful' },
  { name: 'Asset', category: 'Comic & Playful' },
  { name: 'Akronim', category: 'Comic & Playful' },
  { name: 'Aubrey', category: 'Comic & Playful' },
  { name: 'Galindo', category: 'Comic & Playful' },
  { name: 'Geostar', category: 'Comic & Playful' },
  { name: 'Geostar Fill', category: 'Comic & Playful' },
  { name: 'Faster One', category: 'Comic & Playful' },
  { name: 'Plaster', category: 'Comic & Playful' },
  { name: 'Sarina', category: 'Comic & Playful' },
  { name: 'Monofett', category: 'Comic & Playful' },
  { name: 'Hanalei', category: 'Comic & Playful' },
  { name: 'Hanalei Fill', category: 'Comic & Playful' },
  { name: 'Miltonian', category: 'Comic & Playful' },
  { name: 'Miltonian Tattoo', category: 'Comic & Playful' },
  { name: 'Kranky', category: 'Comic & Playful' },
  { name: 'Bungee', category: 'Comic & Playful' },
  { name: 'Bungee Shade', category: 'Comic & Playful' },
  { name: 'Bungee Inline', category: 'Comic & Playful' },
  { name: 'Bungee Outline', category: 'Comic & Playful' },
  { name: 'Black Ops One', category: 'Comic & Playful' },
  { name: 'Bowlby One', category: 'Comic & Playful' },
  { name: 'Bowlby One SC', category: 'Comic & Playful' },
  { name: 'Salsa', category: 'Comic & Playful' },
  { name: 'Rum Raisin', category: 'Comic & Playful' },
  { name: 'Princess Sofia', category: 'Comic & Playful' },
  { name: 'Henny Penny', category: 'Comic & Playful' },
  { name: 'Fondamento', category: 'Comic & Playful' },
  { name: 'Supermercado One', category: 'Comic & Playful' },
  { name: 'Risque', category: 'Comic & Playful' },
  { name: 'MedievalSharp', category: 'Comic & Playful' },
  { name: 'Balsamiq Sans', category: 'Comic & Playful' },
  { name: 'Baloo 2', category: 'Comic & Playful' },

  // --- Storybook Serif (100 fonts) ---
  { name: 'Lora', category: 'Storybook Serif' },
  { name: 'Merriweather', category: 'Storybook Serif' },
  { name: 'Playfair Display', category: 'Storybook Serif' },
  { name: 'Cinzel', category: 'Storybook Serif' },
  { name: 'EB Garamond', category: 'Storybook Serif' },
  { name: 'Cormorant Garamond', category: 'Storybook Serif' },
  { name: 'PT Serif', category: 'Storybook Serif' },
  { name: 'Libre Baskerville', category: 'Storybook Serif' },
  { name: 'Bitter', category: 'Storybook Serif' },
  { name: 'Bree Serif', category: 'Storybook Serif' },
  { name: 'Arvo', category: 'Storybook Serif' },
  { name: 'Vollkorn', category: 'Storybook Serif' },
  { name: 'Crimson Text', category: 'Storybook Serif' },
  { name: 'Crimson Pro', category: 'Storybook Serif' },
  { name: 'Alegreya', category: 'Storybook Serif' },
  { name: 'Rokkitt', category: 'Storybook Serif' },
  { name: 'Zilla Slab', category: 'Storybook Serif' },
  { name: 'BioRhyme', category: 'Storybook Serif' },
  { name: 'Prata', category: 'Storybook Serif' },
  { name: 'Marcellus', category: 'Storybook Serif' },
  { name: 'Abril Fatface', category: 'Storybook Serif' },
  { name: 'Spectral', category: 'Storybook Serif' },
  { name: 'Faustina', category: 'Storybook Serif' },
  { name: 'Sorts Mill Goudy', category: 'Storybook Serif' },
  { name: 'Cardo', category: 'Storybook Serif' },
  { name: 'Frank Ruhl Libre', category: 'Storybook Serif' },
  { name: 'Domine', category: 'Storybook Serif' },
  { name: 'Glegoo', category: 'Storybook Serif' },
  { name: 'Trocchi', category: 'Storybook Serif' },
  { name: 'Neuton', category: 'Storybook Serif' },
  { name: 'Kotta One', category: 'Storybook Serif' },
  { name: 'Linden Hill', category: 'Storybook Serif' },
  { name: 'Coustard', category: 'Storybook Serif' },
  { name: 'Arapey', category: 'Storybook Serif' },
  { name: 'Quattrocento', category: 'Storybook Serif' },
  { name: 'Goudy Bookletter 1911', category: 'Storybook Serif' },
  { name: 'Alice', category: 'Storybook Serif' },
  { name: 'IM Fell English', category: 'Storybook Serif' },
  { name: 'IM Fell DW Pica', category: 'Storybook Serif' },
  { name: 'IM Fell French Canon', category: 'Storybook Serif' },
  { name: 'IM Fell Great Primer', category: 'Storybook Serif' },
  { name: 'Cinzel Decorative', category: 'Storybook Serif' },
  { name: 'Bellefair', category: 'Storybook Serif' },
  { name: 'Old Standard TT', category: 'Storybook Serif' },
  { name: 'Radley', category: 'Storybook Serif' },
  { name: 'Petrona', category: 'Storybook Serif' },
  { name: 'Castoro', category: 'Storybook Serif' },
  { name: 'Almendra', category: 'Storybook Serif' },
  { name: 'Almendra SC', category: 'Storybook Serif' },
  { name: 'Trirong', category: 'Storybook Serif' },
  { name: 'Taviraj', category: 'Storybook Serif' },
  { name: 'Slabo 27px', category: 'Storybook Serif' },
  { name: 'Kameron', category: 'Storybook Serif' },
  { name: 'Judson', category: 'Storybook Serif' },
  { name: 'Poly', category: 'Storybook Serif' },
  { name: 'Belgrano', category: 'Storybook Serif' },
  { name: 'Marko One', category: 'Storybook Serif' },
  { name: 'Bentham', category: 'Storybook Serif' },
  { name: 'Montaga', category: 'Storybook Serif' },
  { name: 'Ledger', category: 'Storybook Serif' },
  { name: 'Suranna', category: 'Storybook Serif' },
  { name: 'Vidaloka', category: 'Storybook Serif' },
  { name: 'Oranienbaum', category: 'Storybook Serif' },
  { name: 'Lusitana', category: 'Storybook Serif' },
  { name: 'Headland One', category: 'Storybook Serif' },
  { name: 'Buenard', category: 'Storybook Serif' },
  { name: 'Port Lligat Slab', category: 'Storybook Serif' },
  { name: 'Rozha One', category: 'Storybook Serif' },
  { name: 'Halant', category: 'Storybook Serif' },
  { name: 'Kurale', category: 'Storybook Serif' },
  { name: 'Rasa', category: 'Storybook Serif' },
  { name: 'Yrsa', category: 'Storybook Serif' },
  { name: 'Besley', category: 'Storybook Serif' },
  { name: 'Fraunces', category: 'Storybook Serif' },
  { name: 'Newsreader', category: 'Storybook Serif' },
  { name: 'Bodoni Moda', category: 'Storybook Serif' },
  { name: 'Brygada 1918', category: 'Storybook Serif' },
  { name: 'Castoro Titling', category: 'Storybook Serif' },
  { name: 'Gilda Display', category: 'Storybook Serif' },
  { name: 'Stint Ultra Expanded', category: 'Storybook Serif' },
  { name: 'Pridi', category: 'Storybook Serif' },
  { name: 'Maitree', category: 'Storybook Serif' },
  { name: 'Stoke', category: 'Storybook Serif' },
  { name: 'Antic Slab', category: 'Storybook Serif' },
  { name: 'Unna', category: 'Storybook Serif' },
  { name: 'Chonburi', category: 'Storybook Serif' },
  { name: 'Vesper Libre', category: 'Storybook Serif' },
  { name: 'Andada Pro', category: 'Storybook Serif' },
  { name: 'GFS Didot', category: 'Storybook Serif' },
  { name: 'GFS Neohellenic', category: 'Storybook Serif' },
  { name: 'Caudex', category: 'Storybook Serif' },
  { name: 'Bona Nova', category: 'Storybook Serif' },
  { name: 'Cormorant', category: 'Storybook Serif' },
  { name: 'Cormorant SC', category: 'Storybook Serif' },
  { name: 'Cormorant Infant', category: 'Storybook Serif' },
  { name: 'Cormorant Unicase', category: 'Storybook Serif' },
  { name: 'Cormorant Upright', category: 'Storybook Serif' },
  { name: 'Asar', category: 'Storybook Serif' },
  { name: 'Balthazar', category: 'Storybook Serif' },
  { name: 'Habibi', category: 'Storybook Serif' },

  // --- Friendly Sans (110 fonts) ---
  { name: 'Nunito', category: 'Friendly Sans' },
  { name: 'Nunito Sans', category: 'Friendly Sans' },
  { name: 'Quicksand', category: 'Friendly Sans' },
  { name: 'Comfortaa', category: 'Friendly Sans' },
  { name: 'Outfit', category: 'Friendly Sans' },
  { name: 'Poppins', category: 'Friendly Sans' },
  { name: 'Open Sans', category: 'Friendly Sans' },
  { name: 'Roboto', category: 'Friendly Sans' },
  { name: 'Lato', category: 'Friendly Sans' },
  { name: 'Montserrat', category: 'Friendly Sans' },
  { name: 'Rubik', category: 'Friendly Sans' },
  { name: 'Work Sans', category: 'Friendly Sans' },
  { name: 'Inter', category: 'Friendly Sans' },
  { name: 'Raleway', category: 'Friendly Sans' },
  { name: 'DM Sans', category: 'Friendly Sans' },
  { name: 'Ubuntu', category: 'Friendly Sans' },
  { name: 'Cabin', category: 'Friendly Sans' },
  { name: 'Karla', category: 'Friendly Sans' },
  { name: 'Josefin Sans', category: 'Friendly Sans' },
  { name: 'Fira Sans', category: 'Friendly Sans' },
  { name: 'Barlow', category: 'Friendly Sans' },
  { name: 'PT Sans', category: 'Friendly Sans' },
  { name: 'Mulish', category: 'Friendly Sans' },
  { name: 'Titillium Web', category: 'Friendly Sans' },
  { name: 'Overpass', category: 'Friendly Sans' },
  { name: 'Hind', category: 'Friendly Sans' },
  { name: 'Catamaran', category: 'Friendly Sans' },
  { name: 'Varela Round', category: 'Friendly Sans' },
  { name: 'Dosis', category: 'Friendly Sans' },
  { name: 'Oxygen', category: 'Friendly Sans' },
  { name: 'Prompt', category: 'Friendly Sans' },
  { name: 'Mitr', category: 'Friendly Sans' },
  { name: 'Kanit', category: 'Friendly Sans' },
  { name: 'Yantramanav', category: 'Friendly Sans' },
  { name: 'Assistant', category: 'Friendly Sans' },
  { name: 'Heebo', category: 'Friendly Sans' },
  { name: 'Saira', category: 'Friendly Sans' },
  { name: 'Signika', category: 'Friendly Sans' },
  { name: 'Signika Negative', category: 'Friendly Sans' },
  { name: 'Questrial', category: 'Friendly Sans' },
  { name: 'Exo 2', category: 'Friendly Sans' },
  { name: 'Asap', category: 'Friendly Sans' },
  { name: 'Maven Pro', category: 'Friendly Sans' },
  { name: 'Mplus 1p', category: 'Friendly Sans' },
  { name: 'Noto Sans', category: 'Friendly Sans' },
  { name: 'Palanquin', category: 'Friendly Sans' },
  { name: 'Palanquin Dark', category: 'Friendly Sans' },
  { name: 'Jost', category: 'Friendly Sans' },
  { name: 'Urbanist', category: 'Friendly Sans' },
  { name: 'Be Vietnam Pro', category: 'Friendly Sans' },
  { name: 'Manrope', category: 'Friendly Sans' },
  { name: 'Plus Jakarta Sans', category: 'Friendly Sans' },
  { name: 'Epilogue', category: 'Friendly Sans' },
  { name: 'Sora', category: 'Friendly Sans' },
  { name: 'Red Hat Display', category: 'Friendly Sans' },
  { name: 'Red Hat Text', category: 'Friendly Sans' },
  { name: 'Lexend', category: 'Friendly Sans' },
  { name: 'Lexend Deca', category: 'Friendly Sans' },
  { name: 'Lexend Exa', category: 'Friendly Sans' },
  { name: 'Lexend Giga', category: 'Friendly Sans' },
  { name: 'Lexend Mega', category: 'Friendly Sans' },
  { name: 'Lexend Peta', category: 'Friendly Sans' },
  { name: 'Lexend Tera', category: 'Friendly Sans' },
  { name: 'Lexend Zetta', category: 'Friendly Sans' },
  { name: 'Atkinson Hyperlegible', category: 'Friendly Sans' },
  { name: 'Readex Pro', category: 'Friendly Sans' },
  { name: 'Sen', category: 'Friendly Sans' },
  { name: 'Kumbh Sans', category: 'Friendly Sans' },
  { name: 'Public Sans', category: 'Friendly Sans' },
  { name: 'Albert Sans', category: 'Friendly Sans' },
  { name: 'Figtree', category: 'Friendly Sans' },
  { name: 'Onest', category: 'Friendly Sans' },
  { name: 'Schibsted Grotesk', category: 'Friendly Sans' },
  { name: 'Instrument Sans', category: 'Friendly Sans' },
  { name: 'Geist', category: 'Friendly Sans' },
  { name: 'Hanken Grotesk', category: 'Friendly Sans' },
  { name: 'Radio Canada', category: 'Friendly Sans' },
  { name: 'Spline Sans', category: 'Friendly Sans' },
  { name: 'Space Grotesk', category: 'Friendly Sans' },
  { name: 'Syne', category: 'Friendly Sans' },
  { name: 'Chivo', category: 'Friendly Sans' },
  { name: 'Golos Text', category: 'Friendly Sans' },
  { name: 'Pathway Extreme', category: 'Friendly Sans' },
  { name: 'Afacad', category: 'Friendly Sans' },
  { name: 'Host Grotesk', category: 'Friendly Sans' },
  { name: 'Parkinsans', category: 'Friendly Sans' },
  { name: 'Funnel Sans', category: 'Friendly Sans' },
  { name: 'Funnel Display', category: 'Friendly Sans' },
  { name: 'Mona Sans', category: 'Friendly Sans' },
  { name: 'Hubot Sans', category: 'Friendly Sans' },
  { name: 'Wix Madefor Text', category: 'Friendly Sans' },
  { name: 'Wix Madefor Display', category: 'Friendly Sans' },
  { name: 'Bricolage Grotesque', category: 'Friendly Sans' },
  { name: 'Reddit Sans', category: 'Friendly Sans' },
  { name: 'Reddit Display', category: 'Friendly Sans' },
  { name: 'Shantell Sans', category: 'Friendly Sans' },
  { name: 'Georama', category: 'Friendly Sans' },
  { name: 'Strait', category: 'Friendly Sans' },
  { name: 'Cuprum', category: 'Friendly Sans' },
  { name: 'Economica', category: 'Friendly Sans' },
  { name: 'Scada', category: 'Friendly Sans' },
  { name: 'Didact Gothic', category: 'Friendly Sans' },
  { name: 'Mako', category: 'Friendly Sans' },
  { name: 'Carrois Gothic', category: 'Friendly Sans' },
  { name: 'Basic', category: 'Friendly Sans' },
  { name: 'Antic', category: 'Friendly Sans' },
  { name: 'Coda', category: 'Friendly Sans' },
  { name: 'Kite One', category: 'Friendly Sans' },
  { name: 'Gudea', category: 'Friendly Sans' },
  { name: 'Metrophobic', category: 'Friendly Sans' },

  // --- Handwritten & Cursive (110 fonts) ---
  { name: 'Schoolbell', category: 'Handwritten' },
  { name: 'Indie Flower', category: 'Handwritten' },
  { name: 'Pacifico', category: 'Handwritten' },
  { name: 'Caveat', category: 'Handwritten' },
  { name: 'Shadows Into Light', category: 'Handwritten' },
  { name: 'Shadows Into Light Two', category: 'Handwritten' },
  { name: 'Amatic SC', category: 'Handwritten' },
  { name: 'Dancing Script', category: 'Handwritten' },
  { name: 'Kalam', category: 'Handwritten' },
  { name: 'Permanent Marker', category: 'Handwritten' },
  { name: 'Satisfy', category: 'Handwritten' },
  { name: 'Great Vibes', category: 'Handwritten' },
  { name: 'Sacramento', category: 'Handwritten' },
  { name: 'Courgette', category: 'Handwritten' },
  { name: 'Gloria Hallelujah', category: 'Handwritten' },
  { name: 'Rock Salt', category: 'Handwritten' },
  { name: 'Covered By Your Grace', category: 'Handwritten' },
  { name: 'Yellowtail', category: 'Handwritten' },
  { name: 'Kaushan Script', category: 'Handwritten' },
  { name: 'Handlee', category: 'Handwritten' },
  { name: 'Patrick Hand', category: 'Handwritten' },
  { name: 'Patrick Hand SC', category: 'Handwritten' },
  { name: 'Just Another Hand', category: 'Handwritten' },
  { name: 'Crafty Girls', category: 'Handwritten' },
  { name: 'Short Stack', category: 'Handwritten' },
  { name: 'Walter Turncoat', category: 'Handwritten' },
  { name: 'Coming Soon', category: 'Handwritten' },
  { name: 'Nothing You Could Do', category: 'Handwritten' },
  { name: 'Marck Script', category: 'Handwritten' },
  { name: 'Alex Brush', category: 'Handwritten' },
  { name: 'Allura', category: 'Handwritten' },
  { name: 'Pinyon Script', category: 'Handwritten' },
  { name: 'Bad Script', category: 'Handwritten' },
  { name: 'Calligraffitti', category: 'Handwritten' },
  { name: 'Homemade Apple', category: 'Handwritten' },
  { name: 'Cedarville Cursive', category: 'Handwritten' },
  { name: 'Loved by the King', category: 'Handwritten' },
  { name: 'Reenie Beanie', category: 'Handwritten' },
  { name: 'Waiting for the Sunrise', category: 'Handwritten' },
  { name: 'Dawning of a New Day', category: 'Handwritten' },
  { name: 'Over the Rainbow', category: 'Handwritten' },
  { name: 'Give You Glory', category: 'Handwritten' },
  { name: 'Zeyada', category: 'Handwritten' },
  { name: 'Swanky and Moo Moo', category: 'Handwritten' },
  { name: 'The Girl Next Door', category: 'Handwritten' },
  { name: 'Sue Ellen Francisco', category: 'Handwritten' },
  { name: 'Kristi', category: 'Handwritten' },
  { name: 'Stalemate', category: 'Handwritten' },
  { name: 'Ruthie', category: 'Handwritten' },
  { name: 'Euphoria Script', category: 'Handwritten' },
  { name: 'Arizonia', category: 'Handwritten' },
  { name: 'Bilbo', category: 'Handwritten' },
  { name: 'Bilbo Swash Caps', category: 'Handwritten' },
  { name: 'Mr Dafoe', category: 'Handwritten' },
  { name: 'Mr De Haviland', category: 'Handwritten' },
  { name: 'Mrs Saint Delafield', category: 'Handwritten' },
  { name: 'Monsieur La Doulaise', category: 'Handwritten' },
  { name: 'Miss Fajardose', category: 'Handwritten' },
  { name: 'Meie Script', category: 'Handwritten' },
  { name: 'Aguafina Script', category: 'Handwritten' },
  { name: 'Qwigley', category: 'Handwritten' },
  { name: 'La Belle Aurore', category: 'Handwritten' },
  { name: 'Felipa', category: 'Handwritten' },
  { name: 'Lovers Quarrel', category: 'Handwritten' },
  { name: 'Rouge Script', category: 'Handwritten' },
  { name: 'Italianno', category: 'Handwritten' },
  { name: 'League Script', category: 'Handwritten' },
  { name: 'Condiment', category: 'Handwritten' },
  { name: 'Engagement', category: 'Handwritten' },
  { name: 'Grand Hotel', category: 'Handwritten' },
  { name: 'Niconne', category: 'Handwritten' },
  { name: 'Stint Ultra Condensed', category: 'Handwritten' },
  { name: 'Clicker Script', category: 'Handwritten' },
  { name: 'Meddon', category: 'Handwritten' },
  { name: 'Rancho', category: 'Handwritten' },
  { name: 'Cookie', category: 'Handwritten' },
  { name: 'Tangerine', category: 'Handwritten' },
  { name: 'Parisienne', category: 'Handwritten' },
  { name: 'Herr Von Muellerhoff', category: 'Handwritten' },
  { name: 'Yellowtail', category: 'Handwritten' },
  { name: 'Delius', category: 'Handwritten' },
  { name: 'Delius Swash Caps', category: 'Handwritten' },
  { name: 'Delius Unicase', category: 'Handwritten' },
  { name: 'Neucha', category: 'Handwritten' },
  { name: 'Caveat Brush', category: 'Handwritten' },
  { name: 'Mali', category: 'Handwritten' },
  { name: 'Gaegu', category: 'Handwritten' },
  { name: 'Itim', category: 'Handwritten' },
  { name: 'Sriracha', category: 'Handwritten' },
  { name: 'Pangolin', category: 'Handwritten' },
  { name: 'Klee One', category: 'Handwritten' },
  { name: 'Yuji Boku', category: 'Handwritten' },
  { name: 'Yuji Mai', category: 'Handwritten' },
  { name: 'Yuji Syuku', category: 'Handwritten' },
  { name: 'Shizuru', category: 'Handwritten' },
  { name: 'Delicious Handrawn', category: 'Handwritten' },
  { name: 'Mynerve', category: 'Handwritten' },
  { name: 'Playpen Sans', category: 'Handwritten' },
  { name: 'Architects Daughter', category: 'Handwritten' },
  { name: 'Annie Use Your Telescope', category: 'Handwritten' },
  { name: 'Dekko', category: 'Handwritten' },
  { name: 'Beth Ellen', category: 'Handwritten' },
  { name: 'Liu Jian Mao Cao', category: 'Handwritten' },
  { name: 'Long Cang', category: 'Handwritten' },
  { name: 'Ma Shan Zheng', category: 'Handwritten' },
  { name: 'Zhi Mang Xing', category: 'Handwritten' },
  { name: 'Hi Melody', category: 'Handwritten' },
  { name: 'East Sea Dokdo', category: 'Handwritten' },
  { name: 'Gamja Flower', category: 'Handwritten' },
  { name: 'Poor Story', category: 'Handwritten' },

  // --- Display & Creative (60 fonts) ---
  { name: 'Lobster', category: 'Display & Creative' },
  { name: 'Lobster Two', category: 'Display & Creative' },
  { name: 'Righteous', category: 'Display & Creative' },
  { name: 'Russo One', category: 'Display & Creative' },
  { name: 'Shrikhand', category: 'Display & Creative' },
  { name: 'Alfa Slab One', category: 'Display & Creative' },
  { name: 'Passion One', category: 'Display & Creative' },
  { name: 'Staatliches', category: 'Display & Creative' },
  { name: 'Monoton', category: 'Display & Creative' },
  { name: 'Press Start 2P', category: 'Display & Creative' },
  { name: 'Silkscreen', category: 'Display & Creative' },
  { name: 'VT323', category: 'Display & Creative' },
  { name: 'DotGothic16', category: 'Display & Creative' },
  { name: 'Rubik Glitch', category: 'Display & Creative' },
  { name: 'Rubik Beastly', category: 'Display & Creative' },
  { name: 'Rubik Bubbles', category: 'Display & Creative' },
  { name: 'Rubik Burned', category: 'Display & Creative' },
  { name: 'Rubik Gemstones', category: 'Display & Creative' },
  { name: 'Rubik Iso', category: 'Display & Creative' },
  { name: 'Rubik Marker Hatch', category: 'Display & Creative' },
  { name: 'Rubik Maze', category: 'Display & Creative' },
  { name: 'Rubik Moonrocks', category: 'Display & Creative' },
  { name: 'Rubik Puddles', category: 'Display & Creative' },
  { name: 'Rubik Vinyl', category: 'Display & Creative' },
  { name: 'Rubik Wet Paint', category: 'Display & Creative' },
  { name: 'Honk', category: 'Display & Creative' },
  { name: 'Bungee Spice', category: 'Display & Creative' },
  { name: 'Nabla', category: 'Display & Creative' },
  { name: 'Foldit', category: 'Display & Creative' },
  { name: 'Jacquard 12', category: 'Display & Creative' },
  { name: 'Jacquard 24', category: 'Display & Creative' },
  { name: 'Jacquarda Bastarda 9', category: 'Display & Creative' },
  { name: 'Jersey 10', category: 'Display & Creative' },
  { name: 'Jersey 15', category: 'Display & Creative' },
  { name: 'Jersey 20', category: 'Display & Creative' },
  { name: 'Jersey 25', category: 'Display & Creative' },
  { name: 'Micro 5', category: 'Display & Creative' },
  { name: 'Tiny5', category: 'Display & Creative' },
  { name: 'Sedgwick Ave', category: 'Display & Creative' },
  { name: 'Sedgwick Ave Display', category: 'Display & Creative' },
  { name: 'Megrim', category: 'Display & Creative' },
  { name: 'Kelly Slab', category: 'Display & Creative' },
  { name: 'Uncial Antiqua', category: 'Display & Creative' },
  { name: 'Caesar Dressing', category: 'Display & Creative' },
  { name: 'Rye', category: 'Display & Creative' },
  { name: 'Sancreek', category: 'Display & Creative' },
  { name: 'Sirin Stencil', category: 'Display & Creative' },
  { name: 'Stardos Stencil', category: 'Display & Creative' },
  { name: 'Big Shoulders Display', category: 'Display & Creative' },
  { name: 'Big Shoulders Inline Text', category: 'Display & Creative' },
  { name: 'Big Shoulders Stencil Display', category: 'Display & Creative' },
  { name: 'Seymour One', category: 'Display & Creative' },
  { name: 'Sonsie One', category: 'Display & Creative' },
  { name: 'Spirax', category: 'Display & Creative' },
  { name: 'Federo', category: 'Display & Creative' },
  { name: 'Glass Antiqua', category: 'Display & Creative' },
  { name: 'Fascinate', category: 'Display & Creative' },
  { name: 'Fascinate Inline', category: 'Display & Creative' },
  { name: 'Geostar', category: 'Display & Creative' },
  { name: 'Diplomata', category: 'Display & Creative' },

  // --- Monospace & Code (40 fonts) ---
  { name: 'Space Mono', category: 'Monospace' },
  { name: 'Fira Code', category: 'Monospace' },
  { name: 'JetBrains Mono', category: 'Monospace' },
  { name: 'Inconsolata', category: 'Monospace' },
  { name: 'Source Code Pro', category: 'Monospace' },
  { name: 'Roboto Mono', category: 'Monospace' },
  { name: 'Ubuntu Mono', category: 'Monospace' },
  { name: 'Courier Prime', category: 'Monospace' },
  { name: 'Cutive Mono', category: 'Monospace' },
  { name: 'Share Tech Mono', category: 'Monospace' },
  { name: 'VT323', category: 'Monospace' },
  { name: 'Nova Mono', category: 'Monospace' },
  { name: 'Overpass Mono', category: 'Monospace' },
  { name: 'DM Mono', category: 'Monospace' },
  { name: 'Syne Mono', category: 'Monospace' },
  { name: 'Major Mono Display', category: 'Monospace' },
  { name: 'Fantasque Sans Mono', category: 'Monospace' },
  { name: 'Red Hat Mono', category: 'Monospace' },
  { name: 'B集中 Mono', category: 'Monospace' },
  { name: 'Azeret Mono', category: 'Monospace' },
  { name: 'Martian Mono', category: 'Monospace' },
  { name: 'Geist Mono', category: 'Monospace' },
  { name: 'Commit Mono', category: 'Monospace' },
  { name: 'Victor Mono', category: 'Monospace' },
  { name: 'Fira Mono', category: 'Monospace' },
  { name: 'PT Mono', category: 'Monospace' },
  { name: 'Oxygen Mono', category: 'Monospace' },
  { name: 'Cousine', category: 'Monospace' },
  { name: 'Anonymous Pro', category: 'Monospace' },
  { name: 'Fragment Mono', category: 'Monospace' },
  { name: 'Spline Sans Mono', category: 'Monospace' },
  { name: 'Chivo Mono', category: 'Monospace' },
  { name: 'Kode Mono', category: 'Monospace' },
  { name: 'Sono', category: 'Monospace' },
  { name: 'Workbench', category: 'Monospace' },
  { name: 'Xanh Mono', category: 'Monospace' },
  { name: 'Sometype Mono', category: 'Monospace' },
  { name: 'Ubuntu Sans Mono', category: 'Monospace' },
  { name: 'Reddit Mono', category: 'Monospace' },
  { name: 'Nabla', category: 'Monospace' },
];

// Cache of loaded Google Fonts to avoid redundant <link> tags
const loadedFonts = new Set<string>();

export function loadGoogleFont(fontName: string) {
  if (!fontName || loadedFonts.has(fontName)) return;

  if (fontName.toLowerCase() === 'cortez') {
    try {
      const link = document.createElement('link');
      link.rel = 'stylesheet';
      link.href = 'https://fonts.googleapis.com/css2?family=Courgette&display=swap';
      document.head.appendChild(link);

      const style = document.createElement('style');
      style.textContent = `
        @font-face {
          font-family: 'Cortez';
          src: local('Courgette'), url('https://fonts.gstatic.com/s/courgette/v18/wEO_E1GanKo5qpAZhp5yGg.woff2') format('woff2');
          font-weight: 400;
          font-style: normal;
        }
      `;
      document.head.appendChild(style);
      loadedFonts.add('Cortez');
      loadedFonts.add('cortez');
      return;
    } catch (e) {
      console.warn('Could not load Cortez font:', e);
    }
  }

  const fontConfig = AVAILABLE_FONTS.find((f) => f.name.toLowerCase() === fontName.toLowerCase());
  const exactName = fontConfig ? fontConfig.name : fontName;

  try {
    const formattedFamily = exactName.replace(/ /g, '+');
    const link = document.createElement('link');
    link.rel = 'stylesheet';
    link.href = `https://fonts.googleapis.com/css2?family=${formattedFamily}&display=swap`;
    document.head.appendChild(link);
    loadedFonts.add(exactName);
  } catch (err) {
    console.warn(`Could not load font ${fontName}:`, err);
  }
}

export function loadGoogleFonts(fontNames: string[]) {
  fontNames.forEach((name) => loadGoogleFont(name));
}
